version: "3.7"
services:
    php-fpm:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                USER: ${USER}
                GROUP: ${GROUP}
                PHP_IMAGE: ${PHP_IMAGE}
                XDEBUG_VERSION: ${XDEBUG_VERSION}
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        working_dir: /var/www
        volumes:
            - ../:/var/www:cached

    nginx:
        image: nginx:1.21.5-alpine
        working_dir: /var/www
        volumes:
            - ../:/var/www:cached
            - ./host.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:8000:80" # Laravel bude na porte 8000

    mariadb:
        image: mariadb:10.7.3
        hostname: db
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

    adminer:
        image: adminer
        ports:
            - "127.0.0.1:8081:8080"

    # >>> Pridávame službu pre Node / Vite <<<
    node:
        image: node:18-alpine     # alebo iná verzia node
        working_dir: /var/www
        volumes:
            - ../:/var/www
        # Otvor port 5173 pre Vite dev server (ak chceš HMR z prehliadača)
        ports:
            - "5173:5173"
        # Spustíme npm run dev a necháme ho bežať nepretržite
        command: [ "npm", "run", "dev" ]
        # Ak chceš, aby sa spúšťala služba len po tom, čo je PHP a pod. hotové:
        depends_on:
            - php-fpm
volumes:
    db_data:
